let saludo = "Hola mundo"; 
console.log(typeof saludo);
let edad = 24; 
console.log(typeof edad);
console.log("el tipo de dato es " + typeof (edad));
console.log("el tipo de dato es " + typeof edad);
let nombre = "Luis";
console.log(typeof nombre);
console.log("El tipo de dato de nombre es " + typeof nombre);
let mayor18 = true;
console.log(typeof mayor18);
console.log("El tipo de dato de mayor18 es " + typeof mayor18);
let x;
console.log(typeof x);
console.log("El tipo de dato de x es " + typeof x);
let bateria = "25";
console.log(typeof bateria);
console.log("El tipo de dato de bateria es " + typeof bateria);
let tienesMascotas = "false";
console.log(typeof tienesMascotas);
console.log("El tipo de dato de tienesMascotas es " + typeof tienesMascotas);
let promedio = 238.90;
console.log(typeof promedio);
console.log("El tipo de dato de promedio es " + typeof promedio);
let nada = null;
console.log(typeof nada);
console.log("El tipo de dato de nada es " + typeof nada);
let y;
console.log(typeof y);
console.log("El tipo de dato de y es " + typeof y);

